.PHONY: get_data_from_s2orc uncompress_everything first_filter
.SUFFIXES:

get_data_from_s2orc:
	# Update with personal script sent by Kyle Lo 
	sh presign_urls_dl_s2orc_20200705v1_full_urls_expires_20220907.sh

uncompress_everything:
	gunzip full/metadata/* && \
	gunzip full/pdf_parses/*

first_filter:
	python only_relevant_abstracts.py
